services:
  - type: web
    name: burger-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: JWT_SECRET
        value: 'burguer_station_user'
